
services:

    openrefine:
        container_name: ${REFABES_NAME}
        image: abesesr/openrefine:${OPENREFINE_VERSION}
        mem_limit: ${REFABES_MEM_LIMIT}
        cpus: ${REFABES_CPU_LIMIT}
        volumes:
            - ./volumes/refabes:/mnt/refine
        ports:
            - "${REFABES_PORT}:3333"
        environment:
          REFINE_MEMORY: ${REFABES_MEM_LIMIT}
        restart: unless-stopped
